### ISSUE TITLE
Exception: Local directory does not exists

### ISSUE THREAD

**Issue by webnull** [Panthera-Framework/copysync#1]
```
Traceback (most recent call last):
  File "/usr/local/bin/copysync", line 19, in <module>
    libcopysync.runInstance(True)
  File "/usr/local/lib/python2.7/dist-packages/libcopysync/__init__.py", line 32, in runInstance
    kernel.main()
  File "/usr/local/lib/python2.7/dist-packages/pantheradesktop/kernel.py", line 290, in main
    self.hooking.execute('app.mainloop')
  File "/usr/local/lib/python2.7/dist-packages/pantheradesktop/hooking.py", line 72, in execute
    data = self.hooksList[hookName][func](data)
  File "/usr/local/lib/python2.7/dist-packages/libcopysync/__init__.py", line 430, in mainLoop
    self.filesystemWatchJob()
  File "/usr/local/lib/python2.7/dist-packages/libcopysync/__init__.py", line 302, in filesystemWatchJob
    self.watcher.startWatching(self)
  File "/usr/local/lib/python2.7/dist-packages/libcopysync/watchers/fswatchdog.py", line 19, in startWatching
    observer.schedule(self, path=self.directory, recursive=True)
  File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/api.py", line 327, in schedule
    timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/inotify.py", line 118, in __init__
    watch.is_recursive)
  File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/inotify_buffer.py", line 63, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/inotify_c.py", line 176, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/inotify_c.py", line 351, in _add_dir_watch
    raise OSError('Path is not a directory')
OSError: Path is not a directory
```

**Comment by webnull** [comment]
Fixed.
